name: Generate Artifact

on:
  push:
    branches:
      - main # Sesuaikan dengan branch repositori kalian

jobs:
  #Test-Pipeline:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout Code
  #      uses: actions/checkout@v4
  #
  #    - name: Run Simple Test
  #      run: echo "Test pipeline executed successfully"
  #
  build-app:
    runs-on: ubuntu-latest
    #needs: Test-Pipeline

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Create build artifact
      - name: Build Application
        run: |
          mkdir dist
          echo "<h2>This is the result of an automated build artifact</h2>" > dist/index.html
          echo "Proses Build selesai, sampah dapur telah dibuang!"

      # Step 3: Upload artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hasil-build-web
          path: dist/
          retention-days: 7 # Otomatis dihapus setelah 7 hari agar kuota GitHub aman
